Song.create(name:'Hello World', artist: 'Lil Alvaro', genre: 'Reggaeton', energy_level: 5, song_id: 1)
Song.create(name: 'Champs', artist: 'Andres', genre: 'Pop', energy_level: 4, song_id: 2)
Song.create(name: 'Forking', artist: 'Ryan', genre: 'Pop', energy_level: 4, song_id: 3)
Song.create(name: 'Git busy', artist: 'Sydney', genre: 'Reggae', energy_level: 5, song_id: 4)
Song.create(name: 'Fashionista', artist: 'Ayana', genre: 'Opera', energy_level: 6, song_id: 5)
Song.create(name: 'Back that hash up', artist: 'John', genre: 'Rap', energy_level: 4, song_id: 6)
Song.create(name: 'Do not commit', artist: 'Josh', genre: 'Salsa', energy_level: 5, song_id: 7)
Song.create(name: 'Uptown Funk', artist: 'Bruno Mars', genre: 'Pop', energy_level: 5, song_id: 8)
Song.create(name: 'Thinking Out Loud', artist: 'Ed Sheeran', genre: 'Pop', energy_level: 4, song_id: 9)
Song.create(name: 'Sugar', artist: 'Maroon5', genre: 'R&B', energy_level: 5, song_id: 10)
Song.create(name: 'Where Are U Now', artist: 'Pentagonix', genre: 'R&B', energy_level: 5, song_id: 11)
Song.create(name: 'Honey, I am Good', artist: 'Andy Grammer', genre: 'R&B', energy_level: 6, song_id: 12)
Song.create(name: 'Pull Up', artist: 'Star Studded, Nina Cash', genre: 'R&B', energy_level: 5, song_id: 13)
Song.create(name: 'Intro', artist: 'C-Nile, Lil John & Eastside Boys', genre: 'Pop', energy_level: 6, song_id: 14)
Song.create(name: 'Jai Ho', artist: 'A.R Rahman, Sukhwinder Singh, Tanvi Shak, Mahakakshmi Iyer', genre: 'R&B', energy_level: 6, song_id: 15)
Song.create(name: 'Post To Be', artist: 'Omarion, Chris Brown, Jhene Aiko', genre: 'R&B', energy_level: 5, song_id: 16)
Song.create(name: 'Lean on', artist: 'Major Lazer, MO, DJ Snake', genre: 'House', energy_level: 6, song_id: 17)
Song.create(name: 'Metropolis', artist: 'David Guetta, Nicky Romero', genre: 'Techno', energy_level: 6, song_id: 18)
Song.create(name: '4ware', artist: 'Deadmau5', genre: 'Dance', energy_level: 6, song_id: 19)
Song.create(name: 'Falling', artist: 'Alesso', genre: 'Dance', energy_level: 5, song_id: 20)
Song.create(name: 'The Want', artist: 'Nick Hakim', genre: 'Soul', energy_level: 2, song_id: 21)
Song.create(name: 'Passionfruit', artist: 'Drake', genre: 'Soul', energy_level: 3, song_id: 22)
Song.create(name: 'Gold Coast Sinkin\'', artist: 'Blake Mills', genre: 'Soul', energy_level: 2, song_id: 23)
Song.create(name: 'Get You', artist: 'Daniel Caeser', genre: 'Soul', energy_level: 2, song_id: 24)
Song.create(name: 'Evergreen', artist: 'YEBBA', genre: 'Soul', energy_level: 3, song_id: 25)
Song.create(name: 'Them Changes', artist: 'Thundercat', genre: 'Soul', energy_level: 3, song_id: 26)
Song.create(name: 'Cranes In The Sky', artist: 'Solange', genre: 'Soul', energy_level: 3, song_id: 27)
Song.create(name: 'Next to You', artist: 'Sam Evian', genre: 'Rock', energy_level: 2, song_id: 28)
Song.create(name: 'Quarrel', artist: 'Moses Sumney', genre: 'Soul', energy_level: 2, song_id: 29)
Song.create(name: 'Open', artist: 'Rhye', genre: 'Soul', energy_level: 2, song_id: 30)
Song.create(name: 'Delphine', artist: 'Kadhja Bonet', genre: 'Soul', energy_level: 1, song_id: 31)
Song.create(name: 'Chamber of Reflection', artist: 'Mac DeMarco', genre: 'Soul', energy_level: 2, song_id: 32)
Song.create(name: 'IDK', artist: 'Kiefer', genre: 'Soul', energy_level: 1, song_id: 33)
Song.create(name: 'Focus', artist: 'H.E.R.', genre: 'Soul', energy_level: 1, song_id: 34)
Song.create(name: 'Como Te Quiero', artist: 'Khruangbin', genre: 'Instrumental', energy_level: 1, song_id: 35)
Song.create(name: 'Georgia', artist: 'Emily King', genre: 'Soul', energy_level: 2, song_id: 36)
Song.create(name: 'Didnt Cha Know', artist: 'Erykah Badu', genre: 'Soul', energy_level: 3, song_id: 37)
Song.create(name: 'Sleep', artist: 'Nick Hakim', genre: 'Soul', energy_level: 1, song_id: 38)
Song.create(name: 'The Look of Love', artist: 'Nina Simone', genre: 'Jazz', energy_level: 2, song_id: 39)
Song.create(name: 'Cry Me a River', artist: 'Ella Fitzgerald', genre: 'Jazz', energy_level: 2, song_id: 40)
User.create(name: 'John', user_id: 1)
User.create(name: 'Alvaro', user_id: 2)
