Song.create(name:'Hello Babe', artist: 'Lil Alvaro', genre: 'Reggaeton', energy_level: 5, song_id: 1)
Song.create(name: 'Ruca', artist: 'Andres', genre: 'Salsa', energy_level: 3, song_id: 2)
Song.create(name: 'Let\'s fork', artist: 'Ryan', genre: 'Pop', energy_level: 4, song_id: 3)
Song.create(name: 'Git busy', artist: 'Sydney', genre: 'Reggae', energy_level: 2, song_id: 4)
Song.create(name: 'Your mom', artist: 'Ayana', genre: 'Opera', energy_level: 1, song_id: 5)
Song.create(name: 'Back that hash up', artist: 'John', genre: 'Rap', energy_level: 3, song_id: 6)
Song.create(name: 'Do not commit', artist: 'Josh', genre: 'Salsa', energy_level: 5, song_id: 7)
